spring:
  application:
    name: Kubernetes Engine Chat
    icon: /gcp.png
  thymeleaf:
    enabled: true
    cache:   false
    prefix:  classpath:/templates/
    suffix:  .html
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
  datasource:
    username: user
    password: password
  cloud:
    gcp:
      sql:
        instance-connection-name: my-project-id:my-region:my-instance-name
        database-name: db

management:
  endpoints:
    beans:
      enabled: false
    web:
      base-path: /_ah
      exposure:
        include: '*'

gitter:
  community:      comunity
  token:          token
  oauth:
    key:          oauth-key
    secret:       oauth-secret
    redirect_url: oauth-redirect-url
