#AppEngine configuration file
runtime: custom
env: flex
service: chat-wall-cs
runtime_config:
  jdk: openjdk8
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
handlers:
  - url: /.*
    script: this field is required, but ignored